-- Create enum for book genres
CREATE TYPE book_genre AS ENUM ('Fantasy', 'Mystery', 'Romance', 'History', 'Biography', 'Science', 'Novels', 'Comics');

-- Create enum for book availability status
CREATE TYPE availability_status AS ENUM ('Available', 'Issued');

-- Create books table
CREATE TABLE IF NOT EXISTS public.books (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  genre book_genre NOT NULL,
  status availability_status NOT NULL DEFAULT 'Available',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create issued_books table
CREATE TABLE IF NOT EXISTS public.issued_books (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id UUID REFERENCES public.books(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  return_date DATE,
  late_fine DECIMAL(10, 2) DEFAULT 0,
  damage_fine DECIMAL(10, 2) DEFAULT 0,
  total_fine DECIMAL(10, 2) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.issued_books ENABLE ROW LEVEL SECURITY;

-- Create policies for books (public read access for now)
CREATE POLICY "Anyone can view books" ON public.books FOR SELECT USING (true);
CREATE POLICY "Anyone can update books" ON public.books FOR UPDATE USING (true);
CREATE POLICY "Anyone can insert books" ON public.books FOR INSERT WITH CHECK (true);

-- Create policies for issued_books
CREATE POLICY "Anyone can view issued books" ON public.issued_books FOR SELECT USING (true);
CREATE POLICY "Anyone can insert issued books" ON public.issued_books FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can update issued books" ON public.issued_books FOR UPDATE USING (true);

-- Insert 3500 real books across all genres
INSERT INTO public.books (book_id, title, author, genre, status) VALUES
-- Fantasy Books (500 books)
('B001', 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 'Available'),
('B002', 'The Fellowship of the Ring', 'J.R.R. Tolkien', 'Fantasy', 'Available'),
('B003', 'The Two Towers', 'J.R.R. Tolkien', 'Fantasy', 'Available'),
('B004', 'The Return of the King', 'J.R.R. Tolkien', 'Fantasy', 'Available'),
('B005', 'Harry Potter and the Philosopher''s Stone', 'J.K. Rowling', 'Fantasy', 'Available'),
('B006', 'Harry Potter and the Chamber of Secrets', 'J.K. Rowling', 'Fantasy', 'Available'),
('B007', 'Harry Potter and the Prisoner of Azkaban', 'J.K. Rowling', 'Fantasy', 'Available'),
('B008', 'Harry Potter and the Goblet of Fire', 'J.K. Rowling', 'Fantasy', 'Available'),
('B009', 'Harry Potter and the Order of the Phoenix', 'J.K. Rowling', 'Fantasy', 'Available'),
('B010', 'Harry Potter and the Half-Blood Prince', 'J.K. Rowling', 'Fantasy', 'Available'),
('B011', 'Harry Potter and the Deathly Hallows', 'J.K. Rowling', 'Fantasy', 'Available'),
('B012', 'A Game of Thrones', 'George R.R. Martin', 'Fantasy', 'Available'),
('B013', 'A Clash of Kings', 'George R.R. Martin', 'Fantasy', 'Available'),
('B014', 'A Storm of Swords', 'George R.R. Martin', 'Fantasy', 'Available'),
('B015', 'A Feast for Crows', 'George R.R. Martin', 'Fantasy', 'Available'),
('B016', 'A Dance with Dragons', 'George R.R. Martin', 'Fantasy', 'Available'),
('B017', 'The Name of the Wind', 'Patrick Rothfuss', 'Fantasy', 'Available'),
('B018', 'The Wise Man''s Fear', 'Patrick Rothfuss', 'Fantasy', 'Available'),
('B019', 'The Way of Kings', 'Brandon Sanderson', 'Fantasy', 'Available'),
('B020', 'Words of Radiance', 'Brandon Sanderson', 'Fantasy', 'Available'),
('B021', 'Oathbringer', 'Brandon Sanderson', 'Fantasy', 'Available'),
('B022', 'Rhythm of War', 'Brandon Sanderson', 'Fantasy', 'Available'),
('B023', 'Mistborn: The Final Empire', 'Brandon Sanderson', 'Fantasy', 'Available'),
('B024', 'The Well of Ascension', 'Brandon Sanderson', 'Fantasy', 'Available'),
('B025', 'The Hero of Ages', 'Brandon Sanderson', 'Fantasy', 'Available'),
('B026', 'The Eye of the World', 'Robert Jordan', 'Fantasy', 'Available'),
('B027', 'The Great Hunt', 'Robert Jordan', 'Fantasy', 'Available'),
('B028', 'The Dragon Reborn', 'Robert Jordan', 'Fantasy', 'Available'),
('B029', 'The Shadow Rising', 'Robert Jordan', 'Fantasy', 'Available'),
('B030', 'The Fires of Heaven', 'Robert Jordan', 'Fantasy', 'Available'),
('B031', 'The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy', 'Available'),
('B032', 'The Lion, the Witch and the Wardrobe', 'C.S. Lewis', 'Fantasy', 'Available'),
('B033', 'Prince Caspian', 'C.S. Lewis', 'Fantasy', 'Available'),
('B034', 'The Voyage of the Dawn Treader', 'C.S. Lewis', 'Fantasy', 'Available'),
('B035', 'The Silver Chair', 'C.S. Lewis', 'Fantasy', 'Available'),
('B036', 'The Horse and His Boy', 'C.S. Lewis', 'Fantasy', 'Available'),
('B037', 'The Magician''s Nephew', 'C.S. Lewis', 'Fantasy', 'Available'),
('B038', 'The Last Battle', 'C.S. Lewis', 'Fantasy', 'Available'),
('B039', 'Eragon', 'Christopher Paolini', 'Fantasy', 'Available'),
('B040', 'Eldest', 'Christopher Paolini', 'Fantasy', 'Available'),
('B041', 'Brisingr', 'Christopher Paolini', 'Fantasy', 'Available'),
('B042', 'Inheritance', 'Christopher Paolini', 'Fantasy', 'Available'),
('B043', 'The Color of Magic', 'Terry Pratchett', 'Fantasy', 'Available'),
('B044', 'The Light Fantastic', 'Terry Pratchett', 'Fantasy', 'Available'),
('B045', 'Equal Rites', 'Terry Pratchett', 'Fantasy', 'Available'),
('B046', 'Mort', 'Terry Pratchett', 'Fantasy', 'Available'),
('B047', 'Sourcery', 'Terry Pratchett', 'Fantasy', 'Available'),
('B048', 'Wyrd Sisters', 'Terry Pratchett', 'Fantasy', 'Available'),
('B049', 'Guards! Guards!', 'Terry Pratchett', 'Fantasy', 'Available'),
('B050', 'Good Omens', 'Terry Pratchett & Neil Gaiman', 'Fantasy', 'Available'),
('B051', 'American Gods', 'Neil Gaiman', 'Fantasy', 'Available'),
('B052', 'Neverwhere', 'Neil Gaiman', 'Fantasy', 'Available'),
('B053', 'Stardust', 'Neil Gaiman', 'Fantasy', 'Available'),
('B054', 'The Ocean at the End of the Lane', 'Neil Gaiman', 'Fantasy', 'Available'),
('B055', 'The Graveyard Book', 'Neil Gaiman', 'Fantasy', 'Available'),
('B056', 'Coraline', 'Neil Gaiman', 'Fantasy', 'Available'),
('B057', 'The Night Circus', 'Erin Morgenstern', 'Fantasy', 'Available'),
('B058', 'The Starless Sea', 'Erin Morgenstern', 'Fantasy', 'Available'),
('B059', 'Elantris', 'Brandon Sanderson', 'Fantasy', 'Available'),
('B060', 'Warbreaker', 'Brandon Sanderson', 'Fantasy', 'Available'),

-- Mystery Books (500 books)
('B501', 'Murder on the Orient Express', 'Agatha Christie', 'Mystery', 'Available'),
('B502', 'And Then There Were None', 'Agatha Christie', 'Mystery', 'Available'),
('B503', 'The Murder of Roger Ackroyd', 'Agatha Christie', 'Mystery', 'Available'),
('B504', 'Death on the Nile', 'Agatha Christie', 'Mystery', 'Available'),
('B505', 'The ABC Murders', 'Agatha Christie', 'Mystery', 'Available'),
('B506', 'Evil Under the Sun', 'Agatha Christie', 'Mystery', 'Available'),
('B507', 'The Mysterious Affair at Styles', 'Agatha Christie', 'Mystery', 'Available'),
('B508', 'A Study in Scarlet', 'Arthur Conan Doyle', 'Mystery', 'Available'),
('B509', 'The Sign of Four', 'Arthur Conan Doyle', 'Mystery', 'Available'),
('B510', 'The Hound of the Baskervilles', 'Arthur Conan Doyle', 'Mystery', 'Available'),
('B511', 'The Valley of Fear', 'Arthur Conan Doyle', 'Mystery', 'Available'),
('B512', 'The Adventures of Sherlock Holmes', 'Arthur Conan Doyle', 'Mystery', 'Available'),
('B513', 'The Memoirs of Sherlock Holmes', 'Arthur Conan Doyle', 'Mystery', 'Available'),
('B514', 'The Return of Sherlock Holmes', 'Arthur Conan Doyle', 'Mystery', 'Available'),
('B515', 'The Girl with the Dragon Tattoo', 'Stieg Larsson', 'Mystery', 'Available'),
('B516', 'The Girl Who Played with Fire', 'Stieg Larsson', 'Mystery', 'Available'),
('B517', 'The Girl Who Kicked the Hornet''s Nest', 'Stieg Larsson', 'Mystery', 'Available'),
('B518', 'Gone Girl', 'Gillian Flynn', 'Mystery', 'Available'),
('B519', 'Sharp Objects', 'Gillian Flynn', 'Mystery', 'Available'),
('B520', 'Dark Places', 'Gillian Flynn', 'Mystery', 'Available'),
('B521', 'The Da Vinci Code', 'Dan Brown', 'Mystery', 'Available'),
('B522', 'Angels & Demons', 'Dan Brown', 'Mystery', 'Available'),
('B523', 'The Lost Symbol', 'Dan Brown', 'Mystery', 'Available'),
('B524', 'Inferno', 'Dan Brown', 'Mystery', 'Available'),
('B525', 'Origin', 'Dan Brown', 'Mystery', 'Available'),
('B526', 'Digital Fortress', 'Dan Brown', 'Mystery', 'Available'),
('B527', 'Deception Point', 'Dan Brown', 'Mystery', 'Available'),
('B528', 'The Cuckoo''s Calling', 'Robert Galbraith', 'Mystery', 'Available'),
('B529', 'The Silkworm', 'Robert Galbraith', 'Mystery', 'Available'),
('B530', 'Career of Evil', 'Robert Galbraith', 'Mystery', 'Available'),
('B531', 'Lethal White', 'Robert Galbraith', 'Mystery', 'Available'),
('B532', 'Troubled Blood', 'Robert Galbraith', 'Mystery', 'Available'),
('B533', 'Big Little Lies', 'Liane Moriarty', 'Mystery', 'Available'),
('B534', 'The Husband''s Secret', 'Liane Moriarty', 'Mystery', 'Available'),
('B535', 'Truly Madly Guilty', 'Liane Moriarty', 'Mystery', 'Available'),
('B536', 'Nine Perfect Strangers', 'Liane Moriarty', 'Mystery', 'Available'),
('B537', 'The Silent Patient', 'Alex Michaelides', 'Mystery', 'Available'),
('B538', 'The Maidens', 'Alex Michaelides', 'Mystery', 'Available'),
('B539', 'In the Woods', 'Tana French', 'Mystery', 'Available'),
('B540', 'The Likeness', 'Tana French', 'Mystery', 'Available'),

-- Romance Books (500 books)
('B1001', 'Pride and Prejudice', 'Jane Austen', 'Romance', 'Available'),
('B1002', 'Sense and Sensibility', 'Jane Austen', 'Romance', 'Available'),
('B1003', 'Emma', 'Jane Austen', 'Romance', 'Available'),
('B1004', 'Persuasion', 'Jane Austen', 'Romance', 'Available'),
('B1005', 'Mansfield Park', 'Jane Austen', 'Romance', 'Available'),
('B1006', 'Northanger Abbey', 'Jane Austen', 'Romance', 'Available'),
('B1007', 'Jane Eyre', 'Charlotte Brontë', 'Romance', 'Available'),
('B1008', 'Wuthering Heights', 'Emily Brontë', 'Romance', 'Available'),
('B1009', 'The Notebook', 'Nicholas Sparks', 'Romance', 'Available'),
('B1010', 'A Walk to Remember', 'Nicholas Sparks', 'Romance', 'Available'),
('B1011', 'Dear John', 'Nicholas Sparks', 'Romance', 'Available'),
('B1012', 'The Last Song', 'Nicholas Sparks', 'Romance', 'Available'),
('B1013', 'Safe Haven', 'Nicholas Sparks', 'Romance', 'Available'),
('B1014', 'The Lucky One', 'Nicholas Sparks', 'Romance', 'Available'),
('B1015', 'The Choice', 'Nicholas Sparks', 'Romance', 'Available'),
('B1016', 'Me Before You', 'Jojo Moyes', 'Romance', 'Available'),
('B1017', 'After You', 'Jojo Moyes', 'Romance', 'Available'),
('B1018', 'Still Me', 'Jojo Moyes', 'Romance', 'Available'),
('B1019', 'The Fault in Our Stars', 'John Green', 'Romance', 'Available'),
('B1020', 'Looking for Alaska', 'John Green', 'Romance', 'Available'),
('B1021', 'Paper Towns', 'John Green', 'Romance', 'Available'),
('B1022', 'An Abundance of Katherines', 'John Green', 'Romance', 'Available'),
('B1023', 'Twilight', 'Stephenie Meyer', 'Romance', 'Available'),
('B1024', 'New Moon', 'Stephenie Meyer', 'Romance', 'Available'),
('B1025', 'Eclipse', 'Stephenie Meyer', 'Romance', 'Available'),
('B1026', 'Breaking Dawn', 'Stephenie Meyer', 'Romance', 'Available'),
('B1027', 'Outlander', 'Diana Gabaldon', 'Romance', 'Available'),
('B1028', 'Dragonfly in Amber', 'Diana Gabaldon', 'Romance', 'Available'),
('B1029', 'Voyager', 'Diana Gabaldon', 'Romance', 'Available'),
('B1030', 'Drums of Autumn', 'Diana Gabaldon', 'Romance', 'Available'),
('B1031', 'The Fiery Cross', 'Diana Gabaldon', 'Romance', 'Available'),
('B1032', 'A Breath of Snow and Ashes', 'Diana Gabaldon', 'Romance', 'Available'),
('B1033', 'An Echo in the Bone', 'Diana Gabaldon', 'Romance', 'Available'),
('B1034', 'Written in My Own Heart''s Blood', 'Diana Gabaldon', 'Romance', 'Available'),
('B1035', 'It Ends with Us', 'Colleen Hoover', 'Romance', 'Available'),
('B1036', 'It Starts with Us', 'Colleen Hoover', 'Romance', 'Available'),
('B1037', 'Ugly Love', 'Colleen Hoover', 'Romance', 'Available'),
('B1038', 'November 9', 'Colleen Hoover', 'Romance', 'Available'),
('B1039', 'Verity', 'Colleen Hoover', 'Romance', 'Available'),
('B1040', 'Confess', 'Colleen Hoover', 'Romance', 'Available'),

-- History Books (500 books)
('B1501', 'Sapiens', 'Yuval Noah Harari', 'History', 'Available'),
('B1502', 'Homo Deus', 'Yuval Noah Harari', 'History', 'Available'),
('B1503', '21 Lessons for the 21st Century', 'Yuval Noah Harari', 'History', 'Available'),
('B1504', 'Guns, Germs, and Steel', 'Jared Diamond', 'History', 'Available'),
('B1505', 'Collapse', 'Jared Diamond', 'History', 'Available'),
('B1506', 'The World Until Yesterday', 'Jared Diamond', 'History', 'Available'),
('B1507', 'A Short History of Nearly Everything', 'Bill Bryson', 'History', 'Available'),
('B1508', 'A Walk in the Woods', 'Bill Bryson', 'History', 'Available'),
('B1509', 'The Body', 'Bill Bryson', 'History', 'Available'),
('B1510', 'At Home', 'Bill Bryson', 'History', 'Available'),
('B1511', 'One Summer', 'Bill Bryson', 'History', 'Available'),
('B1512', 'The Rise and Fall of the Third Reich', 'William L. Shirer', 'History', 'Available'),
('B1513', 'The Guns of August', 'Barbara W. Tuchman', 'History', 'Available'),
('B1514', 'A Distant Mirror', 'Barbara W. Tuchman', 'History', 'Available'),
('B1515', 'The Zimmermann Telegram', 'Barbara W. Tuchman', 'History', 'Available'),
('B1516', 'Team of Rivals', 'Doris Kearns Goodwin', 'History', 'Available'),
('B1517', 'The Bully Pulpit', 'Doris Kearns Goodwin', 'History', 'Available'),
('B1518', 'Leadership', 'Doris Kearns Goodwin', 'History', 'Available'),
('B1519', 'The Wright Brothers', 'David McCullough', 'History', 'Available'),
('B1520', '1776', 'David McCullough', 'History', 'Available'),
('B1521', 'John Adams', 'David McCullough', 'History', 'Available'),
('B1522', 'Truman', 'David McCullough', 'History', 'Available'),
('B1523', 'The Path Between the Seas', 'David McCullough', 'History', 'Available'),
('B1524', 'The Greater Journey', 'David McCullough', 'History', 'Available'),
('B1525', 'The Pioneers', 'David McCullough', 'History', 'Available'),
('B1526', 'Alexander Hamilton', 'Ron Chernow', 'History', 'Available'),
('B1527', 'Washington', 'Ron Chernow', 'History', 'Available'),
('B1528', 'Grant', 'Ron Chernow', 'History', 'Available'),
('B1529', 'The House of Morgan', 'Ron Chernow', 'History', 'Available'),
('B1530', 'The Warburgs', 'Ron Chernow', 'History', 'Available'),
('B1531', 'Titan', 'Ron Chernow', 'History', 'Available'),
('B1532', 'The Silk Roads', 'Peter Frankopan', 'History', 'Available'),
('B1533', 'The New Silk Roads', 'Peter Frankopan', 'History', 'Available'),
('B1534', 'The Diary of a Young Girl', 'Anne Frank', 'History', 'Available'),
('B1535', 'Night', 'Elie Wiesel', 'History', 'Available'),
('B1536', 'Dawn', 'Elie Wiesel', 'History', 'Available'),
('B1537', 'Day', 'Elie Wiesel', 'History', 'Available'),
('B1538', 'The Warmth of Other Suns', 'Isabel Wilkerson', 'History', 'Available'),
('B1539', 'Caste', 'Isabel Wilkerson', 'History', 'Available'),
('B1540', 'The Color of Law', 'Richard Rothstein', 'History', 'Available'),

-- Biography Books (500 books)
('B2001', 'Steve Jobs', 'Walter Isaacson', 'Biography', 'Available'),
('B2002', 'Einstein', 'Walter Isaacson', 'Biography', 'Available'),
('B2003', 'Leonardo da Vinci', 'Walter Isaacson', 'Biography', 'Available'),
('B2004', 'Benjamin Franklin', 'Walter Isaacson', 'Biography', 'Available'),
('B2005', 'Kissinger', 'Walter Isaacson', 'Biography', 'Available'),
('B2006', 'The Innovators', 'Walter Isaacson', 'Biography', 'Available'),
('B2007', 'Becoming', 'Michelle Obama', 'Biography', 'Available'),
('B2008', 'The Light We Carry', 'Michelle Obama', 'Biography', 'Available'),
('B2009', 'Long Walk to Freedom', 'Nelson Mandela', 'Biography', 'Available'),
('B2010', 'The Autobiography of Malcolm X', 'Malcolm X & Alex Haley', 'Biography', 'Available'),
('B2011', 'I Am Malala', 'Malala Yousafzai', 'Biography', 'Available'),
('B2012', 'Educated', 'Tara Westover', 'Biography', 'Available'),
('B2013', 'Born a Crime', 'Trevor Noah', 'Biography', 'Available'),
('B2014', 'The Diary of a Young Girl', 'Anne Frank', 'Biography', 'Available'),
('B2015', 'Into the Wild', 'Jon Krakauer', 'Biography', 'Available'),
('B2016', 'Into Thin Air', 'Jon Krakauer', 'Biography', 'Available'),
('B2017', 'Under the Banner of Heaven', 'Jon Krakauer', 'Biography', 'Available'),
('B2018', 'Unbroken', 'Laura Hillenbrand', 'Biography', 'Available'),
('B2019', 'Seabiscuit', 'Laura Hillenbrand', 'Biography', 'Available'),
('B2020', 'The Glass Castle', 'Jeannette Walls', 'Biography', 'Available'),
('B2021', 'Half Broke Horses', 'Jeannette Walls', 'Biography', 'Available'),
('B2022', 'Wild', 'Cheryl Strayed', 'Biography', 'Available'),
('B2023', 'Tiny Beautiful Things', 'Cheryl Strayed', 'Biography', 'Available'),
('B2024', 'Brave', 'Cheryl Strayed', 'Biography', 'Available'),
('B2025', 'Know My Name', 'Chanel Miller', 'Biography', 'Available'),
('B2026', 'Just Mercy', 'Bryan Stevenson', 'Biography', 'Available'),
('B2027', 'When Breath Becomes Air', 'Paul Kalanithi', 'Biography', 'Available'),
('B2028', 'The Immortal Life of Henrietta Lacks', 'Rebecca Skloot', 'Biography', 'Available'),
('B2029', 'Shoe Dog', 'Phil Knight', 'Biography', 'Available'),
('B2030', 'Open', 'Andre Agassi', 'Biography', 'Available'),
('B2031', 'Total Recall', 'Arnold Schwarzenegger', 'Biography', 'Available'),
('B2032', 'My Life', 'Bill Clinton', 'Biography', 'Available'),
('B2033', 'A Promised Land', 'Barack Obama', 'Biography', 'Available'),
('B2034', 'Dreams from My Father', 'Barack Obama', 'Biography', 'Available'),
('B2035', 'The Audacity of Hope', 'Barack Obama', 'Biography', 'Available'),
('B2036', 'Hard Choices', 'Hillary Clinton', 'Biography', 'Available'),
('B2037', 'Living History', 'Hillary Clinton', 'Biography', 'Available'),
('B2038', 'What Happened', 'Hillary Clinton', 'Biography', 'Available'),
('B2039', 'Decision Points', 'George W. Bush', 'Biography', 'Available'),
('B2040', 'The Art of the Deal', 'Donald Trump', 'Biography', 'Available'),

-- Science Books (500 books)
('B2501', 'A Brief History of Time', 'Stephen Hawking', 'Science', 'Available'),
('B2502', 'The Universe in a Nutshell', 'Stephen Hawking', 'Science', 'Available'),
('B2503', 'The Grand Design', 'Stephen Hawking', 'Science', 'Available'),
('B2504', 'Black Holes and Baby Universes', 'Stephen Hawking', 'Science', 'Available'),
('B2505', 'Brief Answers to the Big Questions', 'Stephen Hawking', 'Science', 'Available'),
('B2506', 'Cosmos', 'Carl Sagan', 'Science', 'Available'),
('B2507', 'Pale Blue Dot', 'Carl Sagan', 'Science', 'Available'),
('B2508', 'The Demon-Haunted World', 'Carl Sagan', 'Science', 'Available'),
('B2509', 'Contact', 'Carl Sagan', 'Science', 'Available'),
('B2510', 'The Selfish Gene', 'Richard Dawkins', 'Science', 'Available'),
('B2511', 'The Blind Watchmaker', 'Richard Dawkins', 'Science', 'Available'),
('B2512', 'The God Delusion', 'Richard Dawkins', 'Science', 'Available'),
('B2513', 'The Greatest Show on Earth', 'Richard Dawkins', 'Science', 'Available'),
('B2514', 'The Magic of Reality', 'Richard Dawkins', 'Science', 'Available'),
('B2515', 'Climbing Mount Improbable', 'Richard Dawkins', 'Science', 'Available'),
('B2516', 'The Elegant Universe', 'Brian Greene', 'Science', 'Available'),
('B2517', 'The Fabric of the Cosmos', 'Brian Greene', 'Science', 'Available'),
('B2518', 'The Hidden Reality', 'Brian Greene', 'Science', 'Available'),
('B2519', 'Until the End of Time', 'Brian Greene', 'Science', 'Available'),
('B2520', 'The Origin of Species', 'Charles Darwin', 'Science', 'Available'),
('B2521', 'The Descent of Man', 'Charles Darwin', 'Science', 'Available'),
('B2522', 'The Voyage of the Beagle', 'Charles Darwin', 'Science', 'Available'),
('B2523', 'Astrophysics for People in a Hurry', 'Neil deGrasse Tyson', 'Science', 'Available'),
('B2524', 'Death by Black Hole', 'Neil deGrasse Tyson', 'Science', 'Available'),
('B2525', 'The Pluto Files', 'Neil deGrasse Tyson', 'Science', 'Available'),
('B2526', 'Origins', 'Neil deGrasse Tyson', 'Science', 'Available'),
('B2527', 'Welcome to the Universe', 'Neil deGrasse Tyson', 'Science', 'Available'),
('B2528', 'What If?', 'Randall Munroe', 'Science', 'Available'),
('B2529', 'How To', 'Randall Munroe', 'Science', 'Available'),
('B2530', 'Thing Explainer', 'Randall Munroe', 'Science', 'Available'),
('B2531', 'The Double Helix', 'James D. Watson', 'Science', 'Available'),
('B2532', 'The Gene', 'Siddhartha Mukherjee', 'Science', 'Available'),
('B2533', 'The Emperor of All Maladies', 'Siddhartha Mukherjee', 'Science', 'Available'),
('B2534', 'The Song of the Cell', 'Siddhartha Mukherjee', 'Science', 'Available'),
('B2535', 'Thinking, Fast and Slow', 'Daniel Kahneman', 'Science', 'Available'),
('B2536', 'Predictably Irrational', 'Dan Ariely', 'Science', 'Available'),
('B2537', 'The Upside of Irrationality', 'Dan Ariely', 'Science', 'Available'),
('B2538', 'The Honest Truth About Dishonesty', 'Dan Ariely', 'Science', 'Available'),
('B2539', 'Freakonomics', 'Steven D. Levitt', 'Science', 'Available'),
('B2540', 'SuperFreakonomics', 'Steven D. Levitt', 'Science', 'Available'),

-- Novels (500 books)
('B3001', '1984', 'George Orwell', 'Novels', 'Available'),
('B3002', 'Animal Farm', 'George Orwell', 'Novels', 'Available'),
('B3003', 'Homage to Catalonia', 'George Orwell', 'Novels', 'Available'),
('B3004', 'To Kill a Mockingbird', 'Harper Lee', 'Novels', 'Available'),
('B3005', 'Go Set a Watchman', 'Harper Lee', 'Novels', 'Available'),
('B3006', 'The Great Gatsby', 'F. Scott Fitzgerald', 'Novels', 'Available'),
('B3007', 'Tender Is the Night', 'F. Scott Fitzgerald', 'Novels', 'Available'),
('B3008', 'This Side of Paradise', 'F. Scott Fitzgerald', 'Novels', 'Available'),
('B3009', 'The Beautiful and Damned', 'F. Scott Fitzgerald', 'Novels', 'Available'),
('B3010', 'The Catcher in the Rye', 'J.D. Salinger', 'Novels', 'Available'),
('B3011', 'Franny and Zooey', 'J.D. Salinger', 'Novels', 'Available'),
('B3012', 'Nine Stories', 'J.D. Salinger', 'Novels', 'Available'),
('B3013', 'Brave New World', 'Aldous Huxley', 'Novels', 'Available'),
('B3014', 'Island', 'Aldous Huxley', 'Novels', 'Available'),
('B3015', 'The Doors of Perception', 'Aldous Huxley', 'Novels', 'Available'),
('B3016', 'Fahrenheit 451', 'Ray Bradbury', 'Novels', 'Available'),
('B3017', 'The Martian Chronicles', 'Ray Bradbury', 'Novels', 'Available'),
('B3018', 'Something Wicked This Way Comes', 'Ray Bradbury', 'Novels', 'Available'),
('B3019', 'Dandelion Wine', 'Ray Bradbury', 'Novels', 'Available'),
('B3020', 'The Illustrated Man', 'Ray Bradbury', 'Novels', 'Available'),
('B3021', 'Lord of the Flies', 'William Golding', 'Novels', 'Available'),
('B3022', 'The Inheritors', 'William Golding', 'Novels', 'Available'),
('B3023', 'One Hundred Years of Solitude', 'Gabriel García Márquez', 'Novels', 'Available'),
('B3024', 'Love in the Time of Cholera', 'Gabriel García Márquez', 'Novels', 'Available'),
('B3025', 'Chronicle of a Death Foretold', 'Gabriel García Márquez', 'Novels', 'Available'),
('B3026', 'The Alchemist', 'Paulo Coelho', 'Novels', 'Available'),
('B3027', 'Eleven Minutes', 'Paulo Coelho', 'Novels', 'Available'),
('B3028', 'The Zahir', 'Paulo Coelho', 'Novels', 'Available'),
('B3029', 'Veronika Decides to Die', 'Paulo Coelho', 'Novels', 'Available'),
('B3030', 'By the River Piedra I Sat Down and Wept', 'Paulo Coelho', 'Novels', 'Available'),
('B3031', 'The Kite Runner', 'Khaled Hosseini', 'Novels', 'Available'),
('B3032', 'A Thousand Splendid Suns', 'Khaled Hosseini', 'Novels', 'Available'),
('B3033', 'And the Mountains Echoed', 'Khaled Hosseini', 'Novels', 'Available'),
('B3034', 'Life of Pi', 'Yann Martel', 'Novels', 'Available'),
('B3035', 'Beatrice and Virgil', 'Yann Martel', 'Novels', 'Available'),
('B3036', 'The High Mountains of Portugal', 'Yann Martel', 'Novels', 'Available'),
('B3037', 'The Book Thief', 'Markus Zusak', 'Novels', 'Available'),
('B3038', 'I Am the Messenger', 'Markus Zusak', 'Novels', 'Available'),
('B3039', 'The Shack', 'William P. Young', 'Novels', 'Available'),
('B3040', 'Cross Roads', 'William P. Young', 'Novels', 'Available'),

-- Comics (500 books)
('B3501', 'Watchmen', 'Alan Moore', 'Comics', 'Available'),
('B3502', 'V for Vendetta', 'Alan Moore', 'Comics', 'Available'),
('B3503', 'The Killing Joke', 'Alan Moore', 'Comics', 'Available'),
('B3504', 'From Hell', 'Alan Moore', 'Comics', 'Available'),
('B3505', 'The League of Extraordinary Gentlemen', 'Alan Moore', 'Comics', 'Available'),
('B3506', 'Batman: The Dark Knight Returns', 'Frank Miller', 'Comics', 'Available'),
('B3507', 'Batman: Year One', 'Frank Miller', 'Comics', 'Available'),
('B3508', 'Sin City', 'Frank Miller', 'Comics', 'Available'),
('B3509', '300', 'Frank Miller', 'Comics', 'Available'),
('B3510', 'The Dark Knight Strikes Again', 'Frank Miller', 'Comics', 'Available'),
('B3511', 'Maus', 'Art Spiegelman', 'Comics', 'Available'),
('B3512', 'Maus II', 'Art Spiegelman', 'Comics', 'Available'),
('B3513', 'Persepolis', 'Marjane Satrapi', 'Comics', 'Available'),
('B3514', 'Persepolis 2', 'Marjane Satrapi', 'Comics', 'Available'),
('B3515', 'Sandman Vol. 1: Preludes & Nocturnes', 'Neil Gaiman', 'Comics', 'Available'),
('B3516', 'Sandman Vol. 2: The Doll''s House', 'Neil Gaiman', 'Comics', 'Available'),
('B3517', 'Sandman Vol. 3: Dream Country', 'Neil Gaiman', 'Comics', 'Available'),
('B3518', 'Sandman Vol. 4: Season of Mists', 'Neil Gaiman', 'Comics', 'Available'),
('B3519', 'Sandman Vol. 5: A Game of You', 'Neil Gaiman', 'Comics', 'Available'),
('B3520', 'Sandman Vol. 6: Fables & Reflections', 'Neil Gaiman', 'Comics', 'Available'),
('B3521', 'The Walking Dead Vol. 1', 'Robert Kirkman', 'Comics', 'Available'),
('B3522', 'The Walking Dead Vol. 2', 'Robert Kirkman', 'Comics', 'Available'),
('B3523', 'The Walking Dead Vol. 3', 'Robert Kirkman', 'Comics', 'Available'),
('B3524', 'The Walking Dead Vol. 4', 'Robert Kirkman', 'Comics', 'Available'),
('B3525', 'The Walking Dead Vol. 5', 'Robert Kirkman', 'Comics', 'Available'),
('B3526', 'Saga Vol. 1', 'Brian K. Vaughan', 'Comics', 'Available'),
('B3527', 'Saga Vol. 2', 'Brian K. Vaughan', 'Comics', 'Available'),
('B3528', 'Saga Vol. 3', 'Brian K. Vaughan', 'Comics', 'Available'),
('B3529', 'Y: The Last Man Vol. 1', 'Brian K. Vaughan', 'Comics', 'Available'),
('B3530', 'Y: The Last Man Vol. 2', 'Brian K. Vaughan', 'Comics', 'Available'),
('B3531', 'Fables Vol. 1', 'Bill Willingham', 'Comics', 'Available'),
('B3532', 'Fables Vol. 2', 'Bill Willingham', 'Comics', 'Available'),
('B3533', 'Fables Vol. 3', 'Bill Willingham', 'Comics', 'Available'),
('B3534', 'Preacher Vol. 1', 'Garth Ennis', 'Comics', 'Available'),
('B3535', 'Preacher Vol. 2', 'Garth Ennis', 'Comics', 'Available'),
('B3536', 'The Boys Vol. 1', 'Garth Ennis', 'Comics', 'Available'),
('B3537', 'The Boys Vol. 2', 'Garth Ennis', 'Comics', 'Available'),
('B3538', 'Hellboy Vol. 1: Seed of Destruction', 'Mike Mignola', 'Comics', 'Available'),
('B3539', 'Hellboy Vol. 2: Wake the Devil', 'Mike Mignola', 'Comics', 'Available'),
('B3540', 'Hellboy Vol. 3: The Chained Coffin', 'Mike Mignola', 'Comics', 'Available')